### ISSUE TITLE
FAQ module - Can't edit previous stored faq_item

### ISSUE THREAD

**Issue by dema501** [magento-devdocs/pagebuilder-examples#10]
In Admin:

1. Go to a CMS page. Add a "FAQ" element to the page.
2. Create faq_item click on settings gear 
3) Save changes for faq_item
4)  click on faq_item settings gear one more time

**Expected result:**
to see settings form again

**Actual result:**
nothing but console error 
> Uncaught TypeError: Cannot read property 'form' of undefined

<img width="500" alt="Screen Shot 2019-05-16 at 11 46 24 AM" src="https://user-images.githubusercontent.com/5056833/57872248-e6c3b800-77d0-11e9-9f84-516109ecfbc6.png">

**Comment by bdenham** [comment]
@dema501. Thanks for reporting this. I’ll take a look and see if I can provide a fix.

**Comment by benoitrenaud** [comment]
Do you have an update on this bug?

**Comment by LilyBergonzat** [comment]
This is because the "appearance" select has `display: none`.

Since there's only one appearance (default), and we don't need a whole visual select for it, I changed the files pagebuilder_faq_form.xml and pagebuilder_faq_item_form.xml so it's just a hidden input:

```xml
    <fieldset name="appearance_fieldset" component="Magento_PageBuilder/js/form/element/dependent-fieldset">
        <settings>
            <label />
        </settings>
        <field name="appearance" formElement="hidden" sortOrder="10">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="default" xsi:type="string">default</item>
                </item>
            </argument>
            <settings>
                <dataType>text</dataType>
            </settings>
        </field>
    </fieldset>
```

And now it works :) !

**Comment by antoniocarrion** [comment]
@LilyWonhalf i tried what you suggest but still not working. Which Magento version are you using? COuld you provide the whole `pagebuilder_faq_form.xml` and `pagebuilder_faq_item_form.xml` files?

**Comment by bdenham** [comment]
Sorry guys, this slipped through the cracks. This happens because default appearances are not defined for the FAQ content type. I will fix this soon.

**Comment by bdenham** [comment]
Resolved by https://github.com/magento-devdocs/pagebuilder-examples/commit/1f2f4cbe38d1cac5fa2cecb3177ed05e5bfa4d90
