### ISSUE TITLE
'Theme/Admin' error

### ISSUE THREAD

**Issue by wasimhc** [magento-devdocs/pagebuilder-examples#35]
Hi, Please let me know if anyone gets "Exception #0 (LogicException): Unable to load theme by specified key: 'Theme/Admin' error in Columns_Extension of https://github.com/magento-devdocs/pagebuilder-examples Thanks.

**Comment by wasimhc** [comment]
To fix this error, I've changed 'Theme/Admin' to 'Magento/Backend' in app/code/Columns/Extension/etc/di.xml and got it fixed.

**Comment by bdenham** [comment]
Thanks for the fix, @wasimhc! Can you submit a PR for this? Thanks.

**Comment by belbiy** [comment]
SeeSee can mm
________________________________

**Comment by wasimhc** [comment]
https://github.com/magento-devdocs/pagebuilder-examples/pull/36
Thank you.

**Comment by bdenham** [comment]
Fixed in PR #36. Thank you, @wasimhc. Sorry for the ridiculous delay. I'll make sure I'm much more attentive moving forward.
