### ISSUE TITLE
On Magento 2.4.5 FAQ items doesn't works

### ISSUE THREAD

**Issue by webdreamsnc** [magento-devdocs/pagebuilder-examples#37]
On Magento 2.4.5 FAQ items doesn't works: FAQ Items are not rendered on backend pagebuilder

**Comment by midhung123** [comment]
Am also facing this issue pagebuilder example not working on version 2.4.5

**Comment by adambois** [comment]
I am using Magento 2.4.5 with PHP8 and the issue seems to be with self closing html tags. For example: `<render args="getOptions().template" />` needs to be changed to `<render args="getOptions().template"></render>`. After I added proper closing tags where needed I got it working. Hope this helps.

**Comment by midhung123** [comment]
yes it seems to be working thanks @adambois

**Comment by webdreamsnc** [comment]
Thank you @adambois, now it seems to be working!

**Comment by dcbaldwin1** [comment]
Also have this same problem with the Quote module. Closing the tags in preview.html does the trick!

**Comment by bdenham** [comment]
Fixed by [@eksiugur](https://github.com/eksiugur) in PR #38 [from eksiugur/37-faq-fix](https://github.com/commerce-docs/pagebuilder-examples/commit/2bda0983d8813de1291b6dbf8f818cf84753f900).

And thank you @adambois for providing an earlier solution.
