### ISSUE TITLE
FAQ component: component content not hidden on page load

### ISSUE THREAD

**Issue by kamephis** [magento-devdocs/pagebuilder-examples#40]
Initially when the FAQ component is loaded in the frontend, the accordions are all open. When the whole page is completely loaded the accordions are closed.

**Steps to reproduce:**

1. Create a FAQ component instance with multiple sections
2. Load the FAQs in the frontend and see, that the component is not correctly rendered on page load
![screen_recording_faq](https://user-images.githubusercontent.com/17859388/209830884-b42419c5-255b-4c88-aebc-f7ef6fd18dd8.gif)

**Comment by bdenham** [comment]
Fixed by @kamephis in PR #41
